<?php

$options = array (
				'NROCOMERCIO' => '',
				'nro_operacion' => '',
				'monto' => '',
				'cuotas' => '',
				'medio_de_pago' => '',
				'email_cliente' => '',
				'param_sitio' => '',	
				'imp_dist' => '',
				'site_dist' => '',
				'id_modalidad' => '',
				'porcentaje' => '',  
				'nro_doc' => '',
				'calle_entrega' => '',
				'nro_puerta' => '',
				'fecha_nacimiento' => '',
				'cod_p1' => '',
				'cod_p2' => '',
				'cod_p3' => '',
				'cod_p4' => '',
				'recargo' => '',
				'fecha_vto' => '',
				'cliente' => '',
				'titular' => '',
				'tipo_toc' => '',
				'nro_doc' => '',
				'fecha_vto' => '',
				'id_plan' => '',
				'vtex1x2x3x4' => '',
				'url_ok' => '',
				'url_error' => '');

?>